# Generated by Django 4.2.3 on 2023-08-30 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactDataType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name="contact",
            name="phone_number",
        ),
        migrations.CreateModel(
            name="ContactData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.CharField(max_length=100)),
                ("contact", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contacts.contact")),
                ("data_type", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contacts.contactdatatype")),
            ],
        ),
    ]
