# Generated by Django 4.2.3 on 2023-08-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("basic", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataStored",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stored_string", models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
