# Generated by Django 4.2.3 on 2023-08-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("basic", "0002_alter_customuser_email_alter_customuser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
