# Generated by Django 4.2.3 on 2023-08-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("basic", "0003_alter_customuser_is_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(default=None, max_length=20, unique=True),
        ),
    ]
