# Generated by Django 4.2.3 on 2023-08-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("basic", "0006_alter_customuser_email_alter_customuser_is_staff_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="state",
            field=models.CharField(choices=[("good", "Good"), ("bad", "Bad")], default="good", max_length=100),
        ),
    ]
