# Generated by Django 4.2.3 on 2023-08-25 06:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("basic", "0008_contact"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contact",
        ),
    ]
